### ISSUE TITLE
Run bars threshold condition should be changed

### ISSUE THREAD

**Issue by proskurin** [hudson-and-thames/mlfinlab#52] opened 2019-04-30 18:54 UTC
expected proportion of buy/sell ticks * expected_buy/sell_volume instead of expected proportion

**Comment by atokuz** [comment] 2019-05-21 21:03
Hi,
I believe the problem is in exp_buy/sell_proportion calculation in _get_expected_imbalance function. Since buy array has 0 for sell ticks and sell array has 0 for buy ticks, calculated ewma result would naturally give the expected value for the next tick. I think there is no need to divide it to total number of ticks. 
[https://github.com/hudson-and-thames/mlfinlab/pull/64](url)

**Comment by proskurin** [comment] 2019-05-22 06:38
Hi!
Did you look at master or dev branch ? In dev branch implementation we don’t put 0 for buy/sell ticks. Current implementation is in dev branch

**Comment by Jackal08** [comment] 2019-07-16 18:58
@proskurin, can we close this ticket?

**Comment by proskurin** [comment] 2019-07-16 19:31
No, we need to complete PR by Atokuz

**Closed** 2019-08-22 07:11 UTC
Labels: bug, good first issue
